### ISSUE TITLE
Use relative image links in README

### ISSUE THREAD

**Issue by drozzy** [redsofa/zmq-soundtouch#14]
The reason the topology image on this page doesn't show up:
https://github.com/redsofa/zmq-soundtouch/tree/v_0.0.1

is because you are linking to absolute url with "master" in it:
https://github.com/redsofa/zmq-soundtouch/blob/master/docs/topology.jpg

Instead, you should use relative links:
https://help.github.com/articles/relative-links-in-readmes/

So it would be:
docs/topology.jpg

**Comment by redsofa** [comment]
Fixed in issue_10 branch. Relative link to docs/topology.png now used.
