### ISSUE TITLE
Secure Pull Socket 

### ISSUE THREAD

**Issue by redsofa** [redsofa/zmq-soundtouch#2]
Pull socket is currently insecure. Change the code stub back to secure...

**Comment by drozzy** [comment]
Will change the _publisher_ to use secure _PULL_ by default.

Thinking of creating a command line option "--insecure" that will allow launching the _publisher_ piece with unsecure _PULL_ socket (for testing purposes).

**Comment by redsofa** [comment]
Yup Great idea.
R.
